print('------------------------------Welcome To My First Program Stranger---------------------------')
print("I want to know you, so...")
name = input("What's your name?")
print(f"Nice to meet you {name}")
print("My name is Max, the same name of my creator")
print(f"Feel free to take a look on my other codes and follow me on Github ;). See you {name}")